spring:
  datasource:
    url: jdbc:h2:~/data/demo
  jpa:
    hibernate:
      ddl-auto: update

  devtools:
    livereload:
      enabled: true

  freemaker:
    cache: false

jwt:
  secret: "FlyingFishermanScheduleMakerCode"

spring.devtools.livereload.enabled: true
---

spring:
  profiles: mariadb
  datasource:
    url: jdbc:mariadb://localhost:3306/test
    username: root
    password: root1234
